import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      // Ignore files generated by Prisma
      "**/src/generated/**",
      "**/prisma/generated/**",
      // Ignore build directories
      "**/.next/**",
      "**/dist/**",
      "**/out/**",
      "**/node_modules/**",
    ]
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
